// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
)

type Task struct {
	ID            int32
	Title         string
	Detail        sql.NullString
	CurrentStatus bool
}
