// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: task.sql

package database

import (
	"context"
	"database/sql"
)

const createTask = `-- name: CreateTask :one
INSERT INTO Tasks (id, title, detail, current_status) 
VALUES ($1, $2, $3, $4) 
RETURNING id, title, detail, current_status
`

type CreateTaskParams struct {
	ID            int32
	Title         string
	Detail        sql.NullString
	CurrentStatus bool
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.ID,
		arg.Title,
		arg.Detail,
		arg.CurrentStatus,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Detail,
		&i.CurrentStatus,
	)
	return i, err
}
